# KNN Algorithm for Handwritten Digit Recognition

## Importing necessary libraries

In [138]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

## Laoding the dataset

In [139]:
col_names = ['para1','para2','para3','para4','para5','para6','para7','para8','para9','para10','para11','para12','para13','para14','para15','para16','target']
dataset = pd.read_csv('pendatatrain.csv',header=None, names=col_names)
dataset.head()

para1  para2  para3  para4  para5  para6  para7  para8  para9  para10  \
0     47    100     27     81     57     37     26      0      0      23   
1      0     89     27    100     42     75     29     45     15      15   
2      0     57     31     68     72     90    100    100     76      75   
3      0    100      7     92      5     68     19     45     86      34   
4      0     67     49     83    100    100     81     80     60      60   

   para11  para12  para13  para14  para15  para16  target  
0      56      53     100      90      40      98       8  
1      37       0      69       2     100       6       2  
2      50      51      28      25      16       0       1  
3     100      45      74      23      67       0       4  
4      40      40      33      20      47       0       1

In [140]:
feature_cols = ['para1','para2','para3','para4','para5','para6','para7','para8','para9','para10','para11','para12','para13','para14','para15','para16','target']
x = dataset[feature_cols]
y = dataset.target

## Splitting the dataset

In [141]:
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0, test_size=0.3)

## Scaling the data

In [142]:
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

C:\Users\rimsha\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\rimsha\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\rimsha\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  This is separate from the ipykernel package so we can avoid doing imports until


## Finding the value of K

In [143]:
import math
math.sqrt(len(y_test))

47.4236228055175

## Define the model and fit the train data into the model

In [144]:
classifier = KNeighborsClassifier(n_neighbors=47,p=10,metric='euclidean')
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
           metric_params=None, n_jobs=None, n_neighbors=47, p=10,
           weights='uniform')

In [145]:
y_pred=classifier.predict(x_test)
print(y_pred)
x_pred=classifier.predict(x_train)
print(x_pred)

[2 8 2 ... 9 6 0]
[7 7 2 ... 0 9 6]


## Evaluating the model

In [146]:
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[225   1   0   0   5   0   0   0   0   0]
 [  0 179  32  10   0   3   1   0   0   0]
 [  0   0 234   0   0   0   0   0   0   0]
 [  0   0   0 203   0   0   0   0   0   0]
 [  0   0   0   0 243   0   0   0   0   0]
 [  0   0   0   5   0 203   0   0   0   0]
 [  0   0   0   0   0   0 216   0   0   0]
 [  0   0   0   0   0   0   0 236   0   0]
 [  0   1   0   0   0   0   1   4 221   6]
 [  1   6   0   0   0   0   0   0   0 213]]


## Finding Accuracy

In [147]:
print(accuracy_score(y_test,y_pred))

0.9662072032014228


In [148]:
print(accuracy_score(y_train,x_pred))

0.971210676835081
